sudo: required

services:
  - docker

before_install:
  - docker build -t charlie_code_kinetic -f Dockerfile-kinetic .

script:
  - docker run charlie_code_kinetic /bin/bash -c "source devel/setup.bash"
