set(_CATKIN_CURRENT_PACKAGE "ublox")
set(ublox_VERSION "0.0.3")
set(ublox_MAINTAINER "Johannes Meyer <nothing@nobody.com>")
set(ublox_PACKAGE_FORMAT "1")
set(ublox_BUILD_DEPENDS )
set(ublox_BUILD_EXPORT_DEPENDS )
set(ublox_BUILDTOOL_DEPENDS "catkin")
set(ublox_BUILDTOOL_EXPORT_DEPENDS )
set(ublox_EXEC_DEPENDS )
set(ublox_RUN_DEPENDS )
set(ublox_TEST_DEPENDS )
set(ublox_DOC_DEPENDS )
set(ublox_DEPRECATED "")