## USB port
port: /dev/ttyUSB0


##### Calibration ####
### accelerometer
accel_x_min: -278.0
accel_x_max: 261.0
accel_y_min: -268.0
accel_y_max: 281.0
accel_z_min: -309.0
accel_z_max: 279.0

### magnetometer
# standard calibration
magn_x_min: -777.0
magn_x_max: 954.0
magn_y_min: -862.0
magn_y_max: 942.0
magn_z_min: -698.0
magn_z_max: 724.0

# extended calibration
calibration_magn_use_extended: false
magn_ellipsoid_center: [0, 0, 0]
magn_ellipsoid_transform: [[0, 0, 0], [0, 0, 0], [0, 0, 0]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: 66.99
gyro_average_offset_y: 47.62
gyro_average_offset_z: 1.79
