# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/AidALM.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/AidEPH.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/AidHUI.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/CfgANT.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/CfgCFG.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/CfgGNSS.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/CfgMSG.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/CfgNAV5.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/CfgNAVX5.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/CfgPRT.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/CfgRATE.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/CfgSBAS.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/MonVER.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/NavCLOCK.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/NavDGPS.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/NavDGPS_SV.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/NavDOP.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/NavPOSECEF.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/NavPOSLLH.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/NavSBAS.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/NavSBAS_SV.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/NavSOL.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/NavSTATUS.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/NavSVINFO.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/NavSVINFO_SV.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/NavTIMEGPS.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/NavTIMEUTC.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/NavVELECEF.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/NavVELNED.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/RxmALM.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/RxmEPH.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/RxmRAW.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/RxmRAW_SV.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/RxmSFRB.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/RxmSVSI.msg;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg/RxmSVSI_SV.msg"
services_str = ""
pkg_name = "ublox_msgs"
dependencies_str = "std_msgs;sensor_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "ublox_msgs;/home/ubuntu/catkin_ws/src/ublox/ublox_msgs/msg;std_msgs;/opt/ros/kinetic/share/std_msgs/cmake/../msg;sensor_msgs;/opt/ros/kinetic/share/sensor_msgs/cmake/../msg;geometry_msgs;/opt/ros/kinetic/share/geometry_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/kinetic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
